
name: 'llama_discrete'

vocab_size: 768
num_layers: 12
dropout_rate: 0.0
time_sequence_length: 2
include_prev_timesteps_actions: false
freeze_backbone: false
use_qformer: false
use_wrist_img: false
use_depth_img: false
input_size: (224,224)